
/*
 * 
 */

package com.sforce.soap._2005._09.outbound;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Tue Jan 20 15:49:54 EST 2015
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "NotificationService", 
                  wsdlLocation = "file:/Users/zoe456/idexx-salesforce/heroku/heroku-spring-cxf-quickstart/src/main/resources/wsdl/testAutomationService.wsdl",
                  targetNamespace = "http://soap.sforce.com/2005/09/outbound") 
public class NotificationService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://soap.sforce.com/2005/09/outbound", "NotificationService");
    public final static QName Notification = new QName("http://soap.sforce.com/2005/09/outbound", "Notification");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/zoe456/idexx-salesforce/heroku/heroku-spring-cxf-quickstart/src/main/resources/wsdl/testAutomationService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/Users/zoe456/idexx-salesforce/heroku/heroku-spring-cxf-quickstart/src/main/resources/wsdl/testAutomationService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public NotificationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns NotificationPort
     */
    @WebEndpoint(name = "Notification")
    public NotificationPort getNotification() {
        return super.getPort(Notification, NotificationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationPort
     */
    @WebEndpoint(name = "Notification")
    public NotificationPort getNotification(WebServiceFeature... features) {
        return super.getPort(Notification, NotificationPort.class, features);
    }

}
