
package com.sforce.soap._2005._09.outbound;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Tue Jan 20 15:49:53 EST 2015
 * Generated source version: 2.2.6
 * 
 */

public final class NotificationPort_Notification_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.sforce.com/2005/09/outbound", "NotificationService");

    private NotificationPort_Notification_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = NotificationService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        NotificationService ss = new NotificationService(wsdlURL, SERVICE_NAME);
        NotificationPort port = ss.getNotification();  
        
        {
        System.out.println("Invoking notifications...");
        java.lang.String _notifications_organizationId = "";
        java.lang.String _notifications_actionId = "";
        java.lang.String _notifications_sessionId = "";
        java.lang.String _notifications_enterpriseUrl = "";
        java.lang.String _notifications_partnerUrl = "";
        java.util.List<com.sforce.soap._2005._09.outbound.TestAutomationCNotification> _notifications_notification = null;
        boolean _notifications__return = port.notifications(_notifications_organizationId, _notifications_actionId, _notifications_sessionId, _notifications_enterpriseUrl, _notifications_partnerUrl, _notifications_notification);
        System.out.println("notifications.result=" + _notifications__return);


        }

        System.exit(0);
    }

}
